### ISSUE TITLE
我应该怎么用它呢？

### ISSUE THREAD

**Issue by xuan0019** [mrchipset/smallchat-win32#1]
您好，在知乎上看到了您的回答，我是一名学生，现在在尝试做一些项目，但是我是第一次

**Comment by xuan0019** [comment]
第一次碰到这种的项目，而之前我一直只有过单个.c文件的编写经历，自己自己找了一些教程但并不奏效，所以想要麻烦您一下来问一些基础的问题

**Comment by mrchipset** [comment]
@xuan0019 同学你好，请问你遇上什么问题了呢？可以发出来一起学习。我如果有空看到留言都会立刻回复。

**Comment by xuan0019** [comment]
谢谢！我现在的问题是我虽然在学校学习了c语言，但是学校所教的内容与实际生产或者工作竞赛中的有很大的偏离。这种情况下，我想要去学习一些可能对我未来的项目或工作更有用的知识，但却没有明确的方向，甚至于我连在网络上自行查找都不知道该搜索什么内容。比如您将antirez的Smallchat移植至win32的开源代码，当我将代码保存到我的电脑上时，我甚至不知道该去如何运行它。我所使用的编译器是VS2022，windows系统，如果您的时间很紧张的话，您只要告诉我一点方向，一点建议——有关于实际生产工作中的方向和建议；如果您的空闲时间稍多的话，敢烦劳您回答我更多的疑惑。谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr. ***@***.***&gt;; 
发送时间: 2023年12月5日(星期二) 晚上9:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mrchipset/smallchat-win32] 我应该怎么用它呢？ (Issue #1)





 
@xuan0019 同学你好，请问你遇上什么问题了呢？可以发出来一起学习。我如果有空看到留言都会立刻回复。

**Comment by mrchipset** [comment]
如果你安装了VS2022，那么就具备了编译这个工程的基本条件。如果VS安装了CMake相关功能，可以直接试试用VS2022打开CMakeLists.txt进行构建。另外你可以了解一下CMake，这个项目的代码是用CMake作为构建工具的。

个人的感受是：实际的生产相较于学校的C语言而言，主要差别是实际的应用场景不同，输入输出不同。学校学的C语言可能就用stdio来读取一些数或者字符做处理，而实际生产中会应对更复杂的情况，更多变的输入（网络、数据库、日志文件等等）、输出和处理逻辑。

如果有兴趣可以私信联系我的zhihu，加个私聊方式沟通。

**Comment by xuan0019** [comment]
谢谢您的建议，我逐个会试试看的！我已经在知乎上找到了您的回答，关注并发送了一条消息，我的ID是zcx0019。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr. ***@***.***&gt;; 
发送时间: 2023年12月5日(星期二) 晚上10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mrchipset/smallchat-win32] 我应该怎么用它呢？ (Issue #1)





 
如果你安装了VS2022，那么就具备了编译这个工程的基本条件。如果VS安装了CMake相关功能，可以直接试试用VS2022打开CMakeLists.txt进行构建。另外你可以了解一下CMake，这个项目的代码是用CMake作为构建工具的。
 
个人的感受是：实际的生产相较于学校的C语言而言，主要差别是实际的应用场景不同，输入输出不同。学校学的C语言可能就用stdio来读取一些数或者字符做处理，而实际生产中会应对更复杂的情况，更多变的输入（网络、数据库、日志文件等等）、输出和处理逻辑。
 
如果有兴趣可以私信联系我的zhihu，加个私聊方式沟通。
