### ISSUE TITLE
一些关于语法的小问题

### ISSUE THREAD

**Issue by Sean537** [mrchipset/smallchat-win32#2]
您好，我试图将您的存储库内的代码适配更老的编译器。这是我的环境：
Windows操作系统
Dev-C++ 5.11 IDE
TDM-GCC 4.9.2编译器
C++11
我创建了一个项目，试图编译，却发现了很多语法错误，如：
`setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes)); // Best effort.`
在这个代码中，setsockopt 函数的第四个参数需要一个 const char* 类型的指针，但是在代码中使用的是 &yes，它是一个 int* 类型的指针。这导致了编译器报错。需要将 &yes 强制转换为 const char* 类型。这样可以让编译器知道你的意图，将 int* 类型的指针转换为 const char* 类型的指针。
就像这样`setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (const char*)&yes, sizeof(yes)); // Best effort.`
等等等等许多语法不规范（我是指在C++11标准下），我解决了七八个，但还是遇到了一个我无法修复的问题，这导致无法编译
![image](https://github.com/mrchipset/smallchat-win32/assets/131773717/6618c1a2-e244-4122-be0b-8e0beed5f955)

错误代码位于smallchat-server.c文件内，150行左右的主函数。
完整编译器提示：C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.o	In function `main':
150		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	multiple definition of `main'
C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-client.o	C:\Users\wusha\Desktop\smallchat-win32-main/smallchat-client.c:240: first defined here
C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.o	In function `initWSA()':
24		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_WSAStartup'
34		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_WSACleanup'
C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.o	In function `cleanWSA()':
43		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_WSACleanup'
C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.o	In function `socketSetNonBlockNoDelay(int)':
62		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_ioctlsocket'
C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.o	In function `createTCPServer(int)':
72		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_socket'
73		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_setsockopt'
77		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_htons'
78		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_htonl'
80		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_bind'
81		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_listen'
C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.o	In function `TCPConnect(char*, int, int)':
106		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_getaddrinfo'
113		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_socket'
123		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_connect'
129		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_closesocket'
139		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_freeaddrinfo'
C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.o	In function `acceptClient(int)':
152		C:\Users\wusha\Desktop\smallchat-win32-main\chatlib.c	undefined reference to `__imp_accept'
C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-client.o	In function `main':
299		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-client.c	undefined reference to `__imp_send'
321		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-client.c	undefined reference to `__imp_select'
328		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-client.c	undefined reference to `__WSAFDIsSet'
330		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-client.c	undefined reference to `__imp_recv'
C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.o	In function `freeClient(client*)':
98		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__imp_closesocket'
C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.o	In function `sendMsgToAllClientsBut(int, char*, unsigned long long)':
142		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__imp_send'
C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.o	In function `main':
182		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__imp_select'
190		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__WSAFDIsSet'
197		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__imp_send'
206		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__WSAFDIsSet'
212		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__imp_recv'
251		C:\Users\wusha\Desktop\smallchat-win32-main\smallchat-server.c	undefined reference to `__imp_send'
C:\Users\wusha\Desktop\smallchat-win32-main\collect2.exe	[Error] ld returned 1 exit status
25		C:\Users\wusha\Desktop\smallchat-win32-main\Makefile.win	recipe for target 'smallchat.exe' failed

请您帮忙看下这个问题可以吗？非常感谢

**Comment by mrchipset** [comment]
你好，

从错误描述看，有两个问题：
1. 把client和server都加载到了同一个工程，导致main函数符号重定义
2. Dev-C没有自动引入Windows 网络相关的库，导致链接器不知道去哪里链接函数
可以先尝试链接这个库`Ws2_32.lib`

**Comment by mrchipset** [comment]
如果没有其他问题和额外回复，我就把这个问题给关闭了
